name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - name: Test if everything is ok
      uses: stefanoeb/jest-action@1.0.0
    - name: Browserify
      run: npm run build
    - name: Publish to npm
      run: |
        yarn install
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
